### ISSUE TITLE
No information about how to use init.coffee

### ISSUE THREAD

**Issue by russlescai** [atom/docs#26]
I have been trying to use init.coffee, but couldn't find any information anywhere on how to use it.

This could be a useful addition to the flight manual.

**Comment by Trudko** [comment]
I am happy to take a look at it during the weekend. I can at least start it :)

**Comment by nathansobo** [comment]
Feel free to post any questions here as you work on that section.

**Comment by izuzak** [comment]
Note: there's a start of such a section, but it seems it's not finished and not included in the book (I'm guessing that happens when you use `xx-` as the prefix of the section?):

https://github.com/atom/docs/blob/master/book/03-hacking-atom/sections/xx-init-file.asc

**Comment by schacon** [comment]
Yeah, this is a small part of what was in the old guides but I couldn't find a good point for it in the new docs. This is mostly because I couldn't find a great reason to use it - like a real example of what someone might put in there. I was thinking of putting it at the end of the chapter, using some of what we've learned to show what might go into a file like this.

@Trudko or @russlescai  could you share some of what you put in your `init.coffee` file? Perhaps we can turn something there into a real example.  And @izuzak is right, the start of the file is already there, it just isn't included in the build yet because it doesn't quite fit.  It shows an example of beeping when Atom loads, which seems a bit silly to me. I would rather have a real example of something useful.

**Comment by russlescai** [comment]
I was thinking of adding a command to run a process.  I assumed it was usually to add a command to add a trivial piece of code. 

in this case I was going to add a command to read the contents of the current editor or open the file in sql management studio.


Not really reusable enough for a package, but scratches a particular itch.

**Comment by izuzak** [comment]
Might be helpful: http://jasonrudolph.com/blog/2014/03/02/defining-atom-commands-in-your-init-script/

**Comment by Trudko** [comment]
@schacon fair point. I already asked this questions my self here you can see some answers  [Share your init.coffee](https://discuss.atom.io/t/share-your-init-coffee/13945).

Personally I use it for something which is specific to my workflow but too small for creating whole package. For example I've created small custom command which opens test fixtures for class . I might created package so others could use it, but it would require extra effort to generalize it for others too.

**Comment by lee-dohm** [comment]
If you search for `add to init.coffee` on Discuss, there are many, many examples. Here are just a few:

* https://discuss.atom.io/t/add-semi-colon-at-end-of-line-and-return/12038/2?u=leedohm
* https://discuss.atom.io/t/dismiss-notifications-with-keyboard/15449/10?u=leedohm
* https://discuss.atom.io/t/quick-close-the-search-panel-results/13289/2?u=leedohm
* https://discuss.atom.io/t/jump-to-start-or-end-of-current-block/11333/2?u=leedohm
* https://discuss.atom.io/t/only-allowing-keybind-to-be-triggered-when-in-command-mode-vim-mode/15496

Some of them are old and would need to be updated, but we're not lacking for examples :grinning:

**Comment by izuzak** [comment]
https://github.com/atom/docs/pull/65 brought back the section on init.coffee and added a more realistic example.
