### ISSUE TITLE
Not a free culture license

### ISSUE THREAD

**Issue by Calinou** [atom/docs#33]
https://github.com/atom/docs/blob/master/LICENSE.asc

The CC BY-NC-SA is not a free culture license. It is suggested to use CC BY-SA (or just CC BY, which makes sense since you're using the MIT license) instead. Like MIT, CC BY is also GPL-compatible.

This may eventually be problematic for inclusion in distribution repositories (like Debian).

For more information on why not to use non-commercial clauses, see: http://freedomdefined.org/Licenses/NC

Using a such a license also kind of a betrayal when saying this on the FAQ:

```
Is Atom open source?

Yes. Atom is MIT licensed and the source is freely available from the atom/atom repository.

All core Atom packages provided by GitHub are also available under the MIT license.
```

**Comment by schacon** [comment]
The core of this is a fair point and we discussed this right before releasing it. I mostly only did that because that's what I use for my Pro Git book and a lot of the template was copied over. I had meant to make that change but it slipped my mind. 

Also, I feel like I should point out that "betrayal" is a really strong and fairly off-putting word for this, especially considering the fact that the docs aren't distributed with the app and Atom is a different project than the documentation. 

![ateamamericafix66c](https://cloud.githubusercontent.com/assets/70/6766552/d0d1f362-d00a-11e4-9aa7-cd29294b6391.gif)

I'll put this on my to do list, unless you want to send a PR I can merge. Thoughts by @atom/core? We all signed off on CC BY-SA right?

**Comment by Calinou** [comment]
Sorry for using “betrayal”, English is not my native language.

**Comment by nathansobo** [comment]
> Thoughts by @atom/core? We all signed off on CC BY-SA right?

@schacon I'm definitely fine using whatever license causes the least friction.

> Sorry for using “betrayal”, English is not my native language.

@Calinou that is understandable. A good word with less strong of a connotation might be "misleading".
